### ISSUE TITLE
gb - Not a valid object name: '_scmb_git_branch_shortcuts'

### ISSUE THREAD

**Issue by rossey** [ndbroadbent/scm_breeze#180]
Since I've updated to version 9913996 the git branch alias `gb` has stopped working for me in bash and zsh with the error:

    fatal: Not a valid object name: '_scmb_git_branch_shortcuts'.

Not sure if I've got an old config or similar?

**Comment by alexconlin** [comment]
I've got the same issue in zsh

**Comment by rossey** [comment]
I'm not sure how to write a failing test for this. I wonder if it's similar to ff4ae793?

**Comment by theonejb** [comment]
I had the same issue. From what I understood, it's happening because `__git_alias: lib/git/aliases.sh:64` expects at least 3 args, since it contains:

    alias_str="$1"; cmd_prefix="$2"; cmd="$3";
    shift 3 2>/dev/null
    cmd_args=$@

but since the alias for gb is defined using

    __git_alias "$git_branch_alias" "_scmb_git_branch_shortcuts": lib/git/branch_shortcuts.sh:41

the `shift 3` doesn't do anything, and `cmd_args` ends up with all the original arguments, making the alias `_scmb_git_branch_shortcuts gb _scmb_git_branch_shortcuts`.

I fixed it by changing `lib/git/branch_shortcuts.sh:41`

    __git_alias "$git_branch_alias" "_scmb_git_branch_shortcuts"

to

    `__git_alias "$git_branch_alias" "_scmb_git_branch_shortcuts" " "

**Comment by rossey** [comment]
Thanks @theonejb, looks like there is a PR for this https://github.com/ndbroadbent/scm_breeze/pull/179

**Comment by stephanvane** [comment]
Hi all,

Maybe a neater solution would be to surround the shift with an if, to check for argument count:

```zsh
if [ $# -gt 2 ]; then
  shift 3 2>/dev/null
  cmd_args=$@
fi
```

What do you think about this? It works for me

**Comment by ndbroadbent** [comment]
@stephanvane - thanks for your suggestion, I pushed the change: 53aba36
